version: "3"

services:
  app:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      command: >
        sh -c " python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py import_provinces &&
                python manage.py import_regencies &&
                python manage.py import_districts &&
                python manage.py import_villages &&
                python manage.py import_groups &&
                python manage.py runserver 0.0.0.0:8000"
      environment:
        - DB_HOST=db
        - DB_NAME=app
        - DB_USER=postgres
        - DB_PASS=passwordrahasia
      depends_on:
        - db
  db:
      image: postgres:10-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=postgres
    

volumes:
  postgres_data: